trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- script: echo Deploying to Azure Web App...
  displayName: 'Deploy'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students'
    appName: 'Gunasekhar'
    package: '.'
